// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin_user.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AdminUser struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	Sex                  string   `protobuf:"bytes,5,opt,name=Sex,proto3" json:"Sex,omitempty"`
	CertNo               string   `protobuf:"bytes,6,opt,name=CertNo,proto3" json:"CertNo,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=Status,proto3" json:"Status,omitempty"`
	JobNo                string   `protobuf:"bytes,8,opt,name=JobNo,proto3" json:"JobNo,omitempty"`
	OrgNo                string   `protobuf:"bytes,9,opt,name=OrgNo,proto3" json:"OrgNo,omitempty"`
	RegisterUri          string   `protobuf:"bytes,10,opt,name=RegisterUri,proto3" json:"RegisterUri,omitempty"`
	JoinTime             string   `protobuf:"bytes,11,opt,name=JoinTime,proto3" json:"JoinTime,omitempty"`
	LeaveTime            string   `protobuf:"bytes,12,opt,name=LeaveTime,proto3" json:"LeaveTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminUser) Reset()         { *m = AdminUser{} }
func (m *AdminUser) String() string { return proto.CompactTextString(m) }
func (*AdminUser) ProtoMessage()    {}
func (*AdminUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebccf7e8e4606b4, []int{0}
}

func (m *AdminUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUser.Unmarshal(m, b)
}
func (m *AdminUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUser.Marshal(b, m, deterministic)
}
func (m *AdminUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUser.Merge(m, src)
}
func (m *AdminUser) XXX_Size() int {
	return xxx_messageInfo_AdminUser.Size(m)
}
func (m *AdminUser) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUser.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUser proto.InternalMessageInfo

func (m *AdminUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AdminUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AdminUser) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AdminUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AdminUser) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *AdminUser) GetCertNo() string {
	if m != nil {
		return m.CertNo
	}
	return ""
}

func (m *AdminUser) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AdminUser) GetJobNo() string {
	if m != nil {
		return m.JobNo
	}
	return ""
}

func (m *AdminUser) GetOrgNo() string {
	if m != nil {
		return m.OrgNo
	}
	return ""
}

func (m *AdminUser) GetRegisterUri() string {
	if m != nil {
		return m.RegisterUri
	}
	return ""
}

func (m *AdminUser) GetJoinTime() string {
	if m != nil {
		return m.JoinTime
	}
	return ""
}

func (m *AdminUser) GetLeaveTime() string {
	if m != nil {
		return m.LeaveTime
	}
	return ""
}

func init() {
	proto.RegisterType((*AdminUser)(nil), "models.AdminUser")
}

func init() { proto.RegisterFile("admin_user.proto", fileDescriptor_1ebccf7e8e4606b4) }

var fileDescriptor_1ebccf7e8e4606b4 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcd, 0x4a, 0x03, 0x41,
	0x0c, 0x80, 0xe9, 0xb6, 0x5d, 0xbb, 0xa9, 0x48, 0x09, 0x22, 0x41, 0x3c, 0x14, 0x4f, 0x9e, 0xbc,
	0xf8, 0x04, 0xe2, 0xa9, 0x45, 0xd6, 0xd2, 0xda, 0xb3, 0x4c, 0x99, 0x50, 0x07, 0xdc, 0x8d, 0x64,
	0xa6, 0xea, 0x3b, 0xf9, 0x92, 0x32, 0x19, 0xff, 0x6e, 0xf9, 0xbe, 0xef, 0x90, 0x10, 0x98, 0x39,
	0xdf, 0x85, 0xfe, 0xe9, 0x10, 0x59, 0xaf, 0x5f, 0x55, 0x92, 0x60, 0xdd, 0x89, 0xe7, 0x97, 0x78,
	0xf9, 0x59, 0x41, 0x73, 0x9b, 0xe3, 0x36, 0xb2, 0xe2, 0x09, 0x54, 0x0b, 0x4f, 0x83, 0xf9, 0xe0,
	0xaa, 0x59, 0x57, 0x0b, 0x8f, 0x08, 0xa3, 0xd6, 0x75, 0x4c, 0x95, 0x19, 0x9b, 0xf1, 0x14, 0xc6,
	0xab, 0x67, 0xe9, 0x99, 0x86, 0x26, 0x0b, 0xe0, 0x39, 0x4c, 0x56, 0x2e, 0xc6, 0x77, 0x51, 0x4f,
	0x23, 0x0b, 0xbf, 0x8c, 0x33, 0x18, 0x6e, 0xf8, 0x83, 0xc6, 0xa6, 0xf3, 0x88, 0x67, 0x50, 0xdf,
	0xb1, 0xa6, 0x56, 0xa8, 0x36, 0xf9, 0x4d, 0xd9, 0x6f, 0x92, 0x4b, 0x87, 0x48, 0x47, 0xc5, 0x17,
	0xca, 0x3b, 0x97, 0xb2, 0x6b, 0x85, 0x26, 0x65, 0xa7, 0x41, 0xb6, 0x0f, 0xba, 0x6f, 0x85, 0x9a,
	0x62, 0x0d, 0x70, 0x0e, 0xd3, 0x35, 0xef, 0x43, 0x4c, 0xac, 0x5b, 0x0d, 0x04, 0xd6, 0xfe, 0xab,
	0x7c, 0xeb, 0x52, 0x42, 0xff, 0x18, 0x3a, 0xa6, 0x69, 0xb9, 0xf5, 0x87, 0xf1, 0x02, 0x9a, 0x7b,
	0x76, 0x6f, 0x6c, 0xf1, 0xd8, 0xe2, 0x9f, 0xd8, 0xd5, 0xf6, 0xbc, 0x9b, 0xaf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x2d, 0xe5, 0x36, 0x2f, 0x50, 0x01, 0x00, 0x00,
}
