// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: admin_user_service.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	models_proto "models/models_proto"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AdminUserService service

type AdminUserService interface {
	AddUser(ctx context.Context, in *models_proto.AdminUser, opts ...client.CallOption) (*models_proto.AdminUser, error)
}

type adminUserService struct {
	c    client.Client
	name string
}

func NewAdminUserService(name string, c client.Client) AdminUserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "services"
	}
	return &adminUserService{
		c:    c,
		name: name,
	}
}

func (c *adminUserService) AddUser(ctx context.Context, in *models_proto.AdminUser, opts ...client.CallOption) (*models_proto.AdminUser, error) {
	req := c.c.NewRequest(c.name, "AdminUserService.AddUser", in)
	out := new(models_proto.AdminUser)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AdminUserService service

type AdminUserServiceHandler interface {
	AddUser(context.Context, *models_proto.AdminUser, *models_proto.AdminUser) error
}

func RegisterAdminUserServiceHandler(s server.Server, hdlr AdminUserServiceHandler, opts ...server.HandlerOption) error {
	type adminUserService interface {
		AddUser(ctx context.Context, in *models_proto.AdminUser, out *models_proto.AdminUser) error
	}
	type AdminUserService struct {
		adminUserService
	}
	h := &adminUserServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AdminUserService{h}, opts...))
}

type adminUserServiceHandler struct {
	AdminUserServiceHandler
}

func (h *adminUserServiceHandler) AddUser(ctx context.Context, in *models_proto.AdminUser, out *models_proto.AdminUser) error {
	return h.AdminUserServiceHandler.AddUser(ctx, in, out)
}
